import Head from "next/head";
import { client } from "../lib/client";
import HeroBanner from "../components/HeroBanner";
import FooterBanner from "../components/FooterBanner";
import Product from "../components/Product";
import Brand from "../components/Brand";

const Home = ({ products, bannerData, brandData }) => {
  return (
    <div className="p-3 m-auto max-w-[1400px] w-full">
      <Head>
        <title>SwagsWear</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner heroBanner={bannerData.length && bannerData[1]} />

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">
              Wear the swag with SwagsWear.com
            </h1>
          </div>
          
          <h1 className="my-20 text-5xl font-bold text-center">BestSellers</h1>
          <div className="flex flex-wrap justify-center -m-4">
            {products?.map((product) => (
              <Product key={product._id} product={product} />
            ))}
          </div>
          <h1 className="my-20 text-5xl font-bold text-center">Brands</h1>
          <div className="flex flex-wrap justify-center -m-4">
            {brandData?.map((item, index) => (
              <Brand key={index} brand={item} />
            ))}
          </div>
        </div>
      </section>

      <FooterBanner footerBanner={bannerData && bannerData[0]} />
    </div>
  );
};

export async function getServerSideProps(context) {
  const query = '*[_type == "product" && bestseller == true]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  const brandQuery = '*[_type == "brand"]';
  const brandData = await client.fetch(brandQuery);

  return {
    props: { products, bannerData, brandData },
  };
}

export default Home;
